### ISSUE TITLE
Signup Not working !!

### ISSUE THREAD

**Issue by rafiulgits** [Maruf520/Custom-SignUp--Django-#1]
https://github.com/Maruf520/Custom-SignUp--Django-/blob/079a144a541d37cfa601ad643e7acf550654ce00/account/forms.py#L18

https://github.com/Maruf520/Custom-SignUp--Django-/blob/079a144a541d37cfa601ad643e7acf550654ce00/account/forms.py#L32

https://github.com/Maruf520/Custom-SignUp--Django-/blob/079a144a541d37cfa601ad643e7acf550654ce00/account/forms.py#L51

these three function should be placed a tab before. Those are under the **SignupForm** class not in **Meta**

**Comment by Maruf520** [comment]
solved
